'use client';

import React, { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { ShieldAlert, AlertTriangle, Printer, User, HeartPulse } from 'lucide-react';
import { mockDb, DEMO_PATIENT } from '@/lib/supabase/service';
import { formatDate } from '@/lib/utils';
import { isDemoMode } from '@/lib/mode';

export default function PublicEmergencyView() {
  const params = useParams();
  const token = params.token as string;

  const [authorized, setAuthorized] = useState<boolean | null>(null);
  const [patient, setPatient] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadPublicEmergency();
  }, [token]);

  const loadPublicEmergency = async () => {
    if (isDemoMode()) {
      const activeTokenRecord = mockDb.query('emergency_access_tokens').select().eq('token', token).single().data;
      if (activeTokenRecord && activeTokenRecord.is_enabled) {
        setAuthorized(true);

        const storedProfile = localStorage.getItem('medmemory_patient_profile');
        const p = storedProfile ? JSON.parse(storedProfile) : DEMO_PATIENT;

        // Apply disclosure config rules in demo mode
        const localConfig = localStorage.getItem('medmemory_emergency_config');
        const config = localConfig ? JSON.parse(localConfig) : {
          show_name: true,
          show_blood_group: true,
          show_allergies: true,
          show_conditions: true,
          show_medications: true,
          show_contact: true,
          show_surgeries: true,
          show_hospitalizations: true
        };

        const redacted: any = {
          fullName: config.show_name ? p.fullName : 'Redacted / Hidden',
          bloodGroup: config.show_blood_group ? { value: p.bloodGroup || 'Unknown', provenance: 'patient-entered' } : { value: 'Redacted / Hidden', provenance: 'redacted' },
          dateOfBirth: p.dateOfBirth,
          knownAllergies: config.show_allergies ? (p.knownAllergies || []).map((v: string) => ({ value: v, provenance: 'patient-entered' })) : [],
          knownChronicConditions: config.show_conditions ? (p.knownChronicConditions || []).map((v: string) => ({ value: v, provenance: 'patient-entered' })) : [],
          currentLongTermMedications: config.show_medications ? (p.currentLongTermMedications || []).map((v: string) => ({ value: v, provenance: 'patient-entered' })) : []
        };

        if (config.show_contact) {
          redacted.emergencyContactName = p.emergencyContactName;
          redacted.emergencyContactPhone = p.emergencyContactPhone;
        }

        setPatient(redacted);
      } else {
        setAuthorized(false);
      }
      setLoading(false);
    } else {
      try {
        const res = await fetch(`/api/public/emergency?token=${token}`);
        if (res.ok) {
          const data = await res.json();
          setAuthorized(true);
          setPatient(data);
        } else {
          setAuthorized(false);
        }
      } catch (err) {
        console.error('Error fetching public emergency details:', err);
        setAuthorized(false);
      } finally {
        setLoading(false);
      }
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-red-600"></div>
      </div>
    );
  }

  if (authorized === false || !patient) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 px-4">
        <div className="max-w-md w-full bg-white border border-slate-200 rounded-3xl p-8 text-center shadow-lg space-y-4">
          <div className="inline-flex p-4 bg-red-50 text-red-655 rounded-2xl">
            <AlertTriangle className="h-8 w-8" />
          </div>
          <h2 className="text-xl font-bold text-slate-850">Access Token Expired or Revoked</h2>
          <p className="text-xs text-slate-500 leading-relaxed">
            The emergency medical portal link has been deactivated or regenerated by the patient. For privacy and data security, full clinical details are hidden.
          </p>
        </div>
      </div>
    );
  }

  // Calculate age
  const dob = new Date(patient.dateOfBirth);
  const ageDiff = Date.now() - dob.getTime();
  const ageDate = new Date(ageDiff);
  const patientAge = Math.abs(ageDate.getUTCFullYear() - 1970);

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-8 px-4 flex flex-col items-center">
      
      {/* Container */}
      <div className="max-w-2xl w-full bg-white dark:bg-slate-900 border-2 border-red-500/20 dark:border-red-500/30 rounded-3xl shadow-xl overflow-hidden print:border-none print:shadow-none">
        
        {/* Urgent header */}
        <div className="bg-red-650 text-white p-5 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <ShieldAlert className="h-7 w-7 animate-pulse" />
            <div>
              <h1 className="text-lg font-black tracking-wider uppercase">MEDICAL ALERT — Emergency ID</h1>
              <span className="text-[10px] text-red-100 font-semibold block">Critical Clinical Patient Profile Summary</span>
            </div>
          </div>
          
          <button
            onClick={handlePrint}
            className="p-2 bg-red-750 hover:bg-red-800 rounded-xl transition-colors text-white border border-red-500/30 print:hidden"
            title="Print record card"
          >
            <Printer className="h-4.5 w-4.5" />
          </button>
        </div>

        {/* Warning banner */}
        <div className="bg-amber-50 dark:bg-slate-800 border-b border-slate-100 dark:border-slate-800 p-4 flex items-start space-x-3">
          <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-slate-655 dark:text-slate-300 leading-relaxed font-semibold">
            Important Information: This summary represents patient-provided critical summaries and verified extraction records. It may not represent the complete diagnostic history.
          </p>
        </div>

        <div className="p-6 md:p-8 space-y-8">
          {/* Patient Details */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 text-sm">
            <div className="space-y-1">
              <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Full Name</span>
              <span className="font-extrabold text-slate-850 dark:text-white text-md">{patient.fullName}</span>
            </div>

            <div className="space-y-1">
              <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Blood Group</span>
              <span className="font-extrabold text-red-650 text-md flex items-center">
                {patient.bloodGroup?.value || patient.bloodGroup || 'Unknown'}
                <span className={`text-[8px] px-1 py-0.2 rounded ml-1.5 font-normal uppercase tracking-normal ${
                  patient.bloodGroup?.provenance === 'document-verified' 
                    ? 'bg-teal-50 dark:bg-teal-950/30 text-teal-600 border border-teal-500/20' 
                    : patient.bloodGroup?.provenance === 'conflict'
                    ? 'bg-red-50 dark:bg-red-950/30 text-red-600 border border-red-500/20 animate-pulse'
                    : 'bg-slate-100 text-slate-550'
                }`}>
                  {patient.bloodGroup?.provenance === 'document-verified' ? 'Document Verified' : patient.bloodGroup?.provenance === 'conflict' ? 'Conflict Warning' : 'Patient Entered'}
                </span>
              </span>
              {patient.bloodGroup?.provenance === 'conflict' && (
                <span className="text-[9px] text-red-500 font-semibold block mt-1">
                  ⚠️ Warning: Patient-reported and lab-verified blood types do not match!
                </span>
              )}
            </div>

            <div className="space-y-1">
              <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Age / DOB</span>
              <span className="font-bold text-slate-800 dark:text-slate-200">{patientAge} Years ({formatDate(patient.dateOfBirth)})</span>
            </div>

            <div className="space-y-1">
              <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Emergency Contact</span>
              {patient.emergencyContactName ? (
                <div className="flex items-center space-x-2 text-slate-805 dark:text-slate-200 font-bold">
                  <User className="h-4 w-4 text-slate-400" />
                  <span>{patient.emergencyContactName} ({patient.emergencyContactPhone})</span>
                </div>
              ) : (
                <span className="text-slate-400 italic">No contact configured.</span>
              )}
            </div>
          </div>

          {/* Medical Alerts (Allergies + Chronic Conditions) */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-6 border-t border-slate-100 dark:border-slate-800 text-xs">
            <div className="space-y-3">
              <span className="text-[10px] text-slate-405 font-bold uppercase tracking-wider block">Critical Allergies</span>
              <div className="flex flex-wrap gap-1.5">
                {patient.knownAllergies?.map((alg: any, i: number) => (
                  <span key={i} className={`px-2.5 py-1 rounded-full font-bold flex items-center ${
                    alg.provenance === 'document-verified'
                      ? 'bg-teal-50 dark:bg-teal-950/20 text-teal-700 dark:text-teal-400 border border-teal-500/10'
                      : 'bg-red-50 dark:bg-red-950/20 text-red-700 dark:text-red-400'
                  }`}>
                    {alg.value || alg}
                    <span className={`text-[8px] ml-1 px-1 rounded uppercase font-normal tracking-normal ${
                      alg.provenance === 'document-verified' ? 'bg-teal-100 text-teal-600' : 'bg-slate-100 text-slate-500'
                    }`}>
                      {alg.provenance === 'document-verified' ? 'Document Verified' : 'Patient Entered'}
                    </span>
                  </span>
                ))}
                {!patient.knownAllergies?.length && (
                  <span className="text-slate-400 italic font-semibold">No verified allergy information was found.</span>
                )}
              </div>
            </div>

            <div className="space-y-3">
              <span className="text-[10px] text-slate-405 font-bold uppercase tracking-wider block">Chronic Conditions</span>
              <div className="flex flex-wrap gap-1.5">
                {patient.knownChronicConditions?.map((cond: any, i: number) => (
                  <span key={i} className={`px-2.5 py-1 rounded-full font-bold flex items-center ${
                    cond.provenance === 'document-verified'
                      ? 'bg-teal-50 dark:bg-teal-950/20 text-teal-700 dark:text-teal-400 border border-teal-500/10'
                      : 'bg-amber-50 dark:bg-amber-950/20 text-amber-700 dark:text-amber-400'
                  }`}>
                    {cond.value || cond}
                    <span className={`text-[8px] ml-1 px-1 rounded uppercase font-normal tracking-normal ${
                      cond.provenance === 'document-verified' ? 'bg-teal-100 text-teal-600' : 'bg-slate-100 text-slate-500'
                    }`}>
                      {cond.provenance === 'document-verified' ? 'Document Verified' : 'Patient Entered'}
                    </span>
                  </span>
                ))}
                {!patient.knownChronicConditions?.length && (
                  <span className="text-slate-400 italic font-semibold">No verified chronic condition record was found.</span>
                )}
              </div>
            </div>
          </div>

          {/* Medications */}
          <div className="pt-6 border-t border-slate-100 dark:border-slate-800 space-y-3 text-xs">
            <span className="text-[10px] text-slate-405 font-bold uppercase tracking-wider block">Current Daily Medications</span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {patient.currentLongTermMedications?.map((med: any, i: number) => (
                <div key={i} className={`p-2.5 border rounded-xl font-bold flex justify-between items-center ${
                  med.provenance === 'document-verified'
                    ? 'bg-teal-50/30 dark:bg-teal-950/10 border-teal-500/20 text-slate-800 dark:text-slate-205'
                    : 'bg-slate-50 dark:bg-slate-850 border-slate-100 dark:border-slate-800 text-slate-800 dark:text-slate-350'
                }`}>
                  <span>{med.value || med}</span>
                  <span className={`text-[8px] px-1 rounded font-normal uppercase tracking-normal ${
                    med.provenance === 'document-verified' ? 'bg-teal-100 text-teal-600' : 'bg-slate-100 text-slate-500'
                  }`}>
                    {med.provenance === 'document-verified' ? 'Document Verified' : 'Patient Entered'}
                  </span>
                </div>
              ))}
              {!patient.currentLongTermMedications?.length && (
                <span className="text-slate-405 italic font-semibold">No verified daily medications was found.</span>
              )}
            </div>
          </div>
        </div>

        {/* Footer disclaimer */}
        <div className="bg-slate-50 dark:bg-slate-850 border-t border-slate-100 dark:border-slate-800 px-6 py-4 flex items-center justify-between text-[10px] text-slate-400 font-medium">
          <div className="flex items-center space-x-1.5">
            <HeartPulse className="h-4 w-4 text-red-500" />
            <span>MedMemory Emergency Summary Portal</span>
          </div>
          <span>Ref: {token.substring(0, 8)}</span>
        </div>

      </div>
    </div>
  );
}
